# Generated by Django 5.1 on 2024-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'posiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'recorridos',
                'managed': False,
            },
        ),
    ]
