# Generated by Django 5.1 on 2024-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(unique=True)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('tipo_carnet', models.CharField(max_length=20)),
                ('legajo_vial', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'conductores',
                'managed': False,
            },
        ),
    ]
