# Generated by Django 5.1 on 2024-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('matricula_vial', models.CharField(max_length=12, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'motores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_nacional', models.CharField(max_length=7, unique=True)),
                ('matrícula_vial', models.CharField(max_length=12, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehiculosMotores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'vehiculos_motores',
                'managed': False,
            },
        ),
    ]
